# Generated by Django 5.1.7 on 2025-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(blank=True, max_length=200, null=True)),
                ('no_cuenta', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('pagado', models.BooleanField(blank=True, null=True)),
                ('cartones', models.IntegerField()),
                ('entregado', models.BooleanField()),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participantes',
            },
        ),
    ]
