# Generated by Django 5.1.7 on 2025-03-25 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_participantes_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
