# Generated by Django 5.1.7 on 2025-03-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_participantes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantes',
            old_name='user',
            new_name='entregado_por',
        ),
    ]
